# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sample_Menu_02_Base.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Intersection_ExtractionBase(object):
    def setupUi(self, Intersection_ExtractionBase):
        Intersection_ExtractionBase.setObjectName("Intersection_ExtractionBase")
        Intersection_ExtractionBase.resize(274, 147)
        self.pushButton_go = QtWidgets.QPushButton(Intersection_ExtractionBase)
        self.pushButton_go.setGeometry(QtCore.QRect(50, 100, 75, 23))
        self.pushButton_go.setObjectName("pushButton_go")
        self.pushButton_cancel = QtWidgets.QPushButton(Intersection_ExtractionBase)
        self.pushButton_cancel.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        # self.lineEdit = QtWidgets.QLineEdit(Intersection_ExtractionBase)
        # self.lineEdit.setGeometry(QtCore.QRect(30, 60, 211, 21))
        # self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Intersection_ExtractionBase)
        self.label.setGeometry(QtCore.QRect(20, 30, 241, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Intersection_ExtractionBase)
        QtCore.QMetaObject.connectSlotsByName(Intersection_ExtractionBase)

    def retranslateUi(self, Intersection_ExtractionBase):
        _translate = QtCore.QCoreApplication.translate
        Intersection_ExtractionBase.setWindowTitle(_translate("Intersection_ExtractionBase", "Form"))
        self.pushButton_go.setText(_translate("Intersection_ExtractionBase", "OK"))
        self.pushButton_cancel.setText(_translate("Intersection_ExtractionBase", "キャンセル"))
        self.label.setText(_translate("Intersection_ExtractionBase", "csvファイルを選択し，交差点抽出を行いますか？"))

"""
class Ui_SampleMenu02Base(object):
    def setupUi(self, SampleMenu02Base):
        SampleMenu02Base.setObjectName("SampleMenu02Base")
        SampleMenu02Base.resize(274, 147)
        self.pushButton_go = QtWidgets.QPushButton(SampleMenu02Base)
        self.pushButton_go.setGeometry(QtCore.QRect(50, 100, 75, 23))
        self.pushButton_go.setObjectName("pushButton_go")
        self.pushButton_cancel = QtWidgets.QPushButton(SampleMenu02Base)
        self.pushButton_cancel.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.lineEdit = QtWidgets.QLineEdit(SampleMenu02Base)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 211, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(SampleMenu02Base)
        self.label.setGeometry(QtCore.QRect(20, 30, 241, 16))
        self.label.setObjectName("label")

        self.retranslateUi(SampleMenu02Base)
        QtCore.QMetaObject.connectSlotsByName(SampleMenu02Base)

    def retranslateUi(self, SampleMenu02Base):
        _translate = QtCore.QCoreApplication.translate
        SampleMenu02Base.setWindowTitle(_translate("SampleMenu02Base", "Form"))
        self.pushButton_go.setText(_translate("SampleMenu02Base", "OK"))
        self.pushButton_cancel.setText(_translate("SampleMenu02Base", "キャンセル"))
        self.label.setText(_translate("SampleMenu02Base", "csvファイルを選択し，交差点抽出を行いますか？"))
"""